person:
  # String
  userName: zhangsan
  # Boolean
  boss: true
  # Date
  birth: 2019/12/09
  # Integer
  age: 18
  # String[]
  #interests: [篮球, 足球]
  interests:
    - 篮球
    - 足球
    - 18
  # List<String>
  animal: [阿猫, 阿狗]
  # Map<String, Object>
#  score:
#    englist: 80
#    math: 90
  score: {k1: v1, k2: v2}
  # Set
  salarys:
    - 9999.98
    - 9999.99
  # Pet对象，里面有两个属性，name和weigth
  pet:
    name: 阿狗
    weight: 99.99
  # Map<String, List<Pet>>
  allPets:
    sick:
      - {name: 阿狗, weight: 99.99}
      - name: 阿猫
        weight: 88.88
      - name: 阿虫
        weight: 77.77
    health:
      - {name: 阿花, weight: 199.99}
      - name: 阿明
        weight: 88.88
      - name: 阿虫
        weight: 77.77

#spring:
#  banner:
#    location: classpath:banner.jpg
#    image:
#      bitdepth: 4
#  cache:
#    type: redis
#    redis:
#      time-to-live: 11000